openapi: 3.0.3
x-stoplight:
  id: y2xy4cvkfra69
info:
  title: task-management
  version: 0.0.1
  description: api description
  contact:
    name: akima1001
    url: 'https://github.com/Mas423'
  license:
    name: MIT
    url: 'https://opensource.org/licenses/mit-license.php'
servers:
  - url: 'http://localhost:11004'
paths:
  /auth/signup:
    post:
      summary: post-auth-signup
      operationId: post-auth-signup
      responses:
        '200':
          description: OK
      tags:
        - auth
      description: 新規ユーザを作成。ログインセッションを発行する。
      requestBody:
        $ref: '#/components/requestBodies/authSignupRequest'
  /auth/login:
    post:
      summary: post-auth-login
      operationId: post-auth-login
      responses:
        '200':
          description: OK
      tags:
        - auth
      requestBody:
        $ref: '#/components/requestBodies/authLoginRequest'
      description: ログインセッションを発行する。
  /auth/logout:
    get:
      summary: get-auth-logout
      tags:
        - auth
      responses:
        '200':
          description: OK
      operationId: get-auth-logout
      parameters:
        - $ref: '#/components/parameters/session'
      description: ログインセッションを削除する。
  /task:
    post:
      summary: post-task
      operationId: post-task
      responses:
        '200':
          description: OK
      tags:
        - task
      requestBody:
        $ref: '#/components/requestBodies/postTaskRequest'
components:
  schemas: {}
  requestBodies:
    authSignupRequest:
      content:
        application/json:
          schema:
            type: object
            properties:
              password:
                type: string
                minLength: 1
                maxLength: 16
                example: password
              userName:
                type: string
                maxLength: 128
                minLength: 1
                example: userName
              emailAddress:
                type: string
                maxLength: 254
                format: email
                example: test@test.com
              telephoneNumber:
                type: string
                maxLength: 18
                example: '0000000000'
            required:
              - password
              - userName
              - emailAddress
              - telephoneNumber
      description: ''
    authLoginRequest:
      content:
        application/json:
          schema:
            type: object
            properties:
              userName:
                type: string
                example: username
                minLength: 1
                maxLength: 128
              password:
                type: string
            required:
              - userName
              - password
    postTaskRequest:
      content:
        application/json:
          schema:
            type: object
            x-examples:
              Example 1:
                createdUserId: ''
                taskName: ''
                expiredOn: ''
                startedAt: ''
                taskLabels:
                  - ''
                assignedUserIds:
                  - ''
                taskStatus: ''
            properties:
              createdUserId:
                type: string
                format: uuid
              taskName:
                type: string
                maxLength: 127
              expiredOn:
                type: string
                format: date
              startedAt:
                type: string
                format: date-time
              taskLabelIds:
                type: array
                maxItems: 8
                uniqueItems: true
                items:
                  type: string
                  maxLength: 32
              assignedUserIds:
                type: array
                maxItems: 8
                uniqueItems: true
                items:
                  type: string
              taskStatusId:
                type: string
                format: uuid
            required:
              - createdUserId
              - taskName
              - expiredOn
              - startedAt
              - taskLabelIds
              - assignedUserIds
              - taskStatusId
  parameters:
    session:
      name: session
      in: cookie
      required: false
      schema:
        type: string
tags:
  - name: auth
  - name: task
