name: nodejs-server-test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:14
        ports:
          - 11002:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: local_tm
        # ヘルスチェック
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: test
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm i --ignore-scripts
      - run: npm run build
      - run: npm run jest
